import { StyleSheet } from "react-native";
import { theme } from "../utils/theme";

const styles = StyleSheet.create({
  imageFadeWrap: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  container: {
    width: "92%",
    alignSelf: "center",
    backgroundColor: theme.card,
    borderRadius: 20,
    overflow: "hidden",
    elevation: 6,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    marginVertical: 18,
    borderWidth: 1,
    borderColor: theme.border,
  },
  imageWrapper: {
    width: "100%",
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
    position: "relative",
  },
  image: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: theme.surface,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  titleOverlay: {
    zIndex: 2,
    alignSelf: "center",
    justifyContent: "flex-end",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 18,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  titleInImage: {
    fontSize: 24,
    fontWeight: "800",
    color: theme.text,
    textAlign: "center",
    letterSpacing: 0.3,
    textShadowColor: "rgba(0,0,0,0.32)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    elevation: 8,
    paddingHorizontal: 4,
  },
  blurOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  blurFill: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  // ...existing styles...
});

export default styles;
